Repository sbb-design-systems/sbb-angular, pull requests merged in 2022-11, with the labels that each got.

#1701 build: migrate GitHub Actions set-output to $GITHUB_OUTPUT
  .github/actions/yarn-install/action.yml
  .github/workflows/maintenance-changelog.yml
  .github/workflows/maintenance-cherry-pick.yml
  .github/workflows/release.yml
Labels: target: 14.x

#1702 docs: display warnings in update guide
  src/showcase/app/howtoupdate/how-to-update.component.html
Labels: target: 14.x

#1690 fix(angular/tooltip): animations running when timeouts haven't elapsed
  src/angular/tooltip/tooltip.spec.ts
  src/angular/tooltip/tooltip.ts
Labels: target: 14.x

#1712 ci: make renovate ignore zone.js
  renovate.json
Labels: target: 14.x

#1714 fix(multiple): add HCM for disabled tabs and steps
  src/angular/processflow/step-header.scss
  src/angular/tabs/_tabs.scss
Labels: target: 14.x

#1715 docs: add v15 update steps
  src/showcase/app/howtoupdate/update-steps.ts
Labels: target: major

#1718 feat(angular/select): add page down/up button functionality
  src/angular/select/select.spec.ts
  src/angular/select/select.ts
Labels: target: major

#1726 ci: don't run scripts in renovate's postUpgradeTasks
  renovate.json
Labels: target: 14.x

#1723 chore(deps): update angular to v15
  package.json
  yarn.lock
Labels: target: major

#1727 fix(angular/select): don't assign typeahead value after blur
  src/angular/select/select.spec.ts
  src/angular/select/select.ts
Labels: target: major

#1739 ci: add lean polyfill for testing
  package.json
  src/angular/config.bzl
  src/angular/core/testing/lean-polyfill/BUILD.bazel
  src/angular/core/testing/lean-polyfill/index.ts
  src/angular/core/testing/lean-polyfill/public-api.ts
  src/angular/schematics/ng-add/index.spec.ts
  src/angular/schematics/ng-add/setup-project.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
  yarn.lock
Labels: target: major

#1741 build: update angular and cdk version range
  RELEASE.md
  packages.bzl
Labels: target: 14.x

#1740 chore: adjust ci workflow after release
  .github/workflows/maintenance-changelog.yml
  .github/workflows/maintenance-tagging.yml
  renovate.json
Labels: target: 15.x
