Repository sbb-design-systems/sbb-angular, pull requests merged in 2022-06, with the labels that each got.

#1482 chore: update checkbox test
  src/angular/checkbox/checkbox.spec.ts
Labels: target: 13.x

#1483 feat(journey-maps): make the home button configurable and refactor viewportOptions
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/constants.ts
  src/journey-maps/angular/services/locale-service.ts
  src/journey-maps/angular/services/map/map-init-service.ts
  src/journey-maps/angular/services/map/map-service.ts
  src/journey-maps/angular/util/typeguard.ts
Labels: target: major

#1499 fix(journey-maps): add missing migration instruction
  src/journey-maps/migrate-from-rokas.md
Labels: target: 13.x

#1500 fix(journey-maps): show "Leit-POIs" for journey based routing
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/map/map-leit-poi-service.ts
Labels: target: major

#1493 chore: remove angular-t9n from renovate ng update
  renovate.json
Labels: target: 13.x

#1487 chore: update project setup script
  src/angular/schematics/ng-add/index.spec.ts
  src/angular/schematics/ng-add/setup-project.ts
Labels: target: major

#1494 chore(stackblitz): update stackblitz assets to v14
  src/showcase/assets/stack-blitz/angular.json
  src/showcase/assets/stack-blitz/package-lock.json
  src/showcase/assets/stack-blitz/package.json
  src/showcase/assets/stack-blitz/src/test.ts
  src/showcase/assets/stack-blitz/tsconfig.json
Labels: target: major

#1495 docs: explicitly declare v13 in migration guide
  src/angular/migration-guide.md
  src/showcase/app/shared/meta.ts
Labels: target: major

#1507 fix(journey-maps): fix internal references
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/journey-maps/angular/public-api.ts
  src/journey-maps/angular/services/map/map-init-service.ts
  src/journey-maps/angular/services/map/map-service.ts
  src/journey-maps/angular/util/typeguard.ts
Labels: target: major

#1509 fix(dialog): avoid colliding symbol names in dialog and lightbox
  src/angular/dialog/dialog-animations.ts
  src/angular/dialog/dialog-config.ts
  src/angular/dialog/dialog-container.ts
  src/angular/lightbox/lightbox-animations.ts
  src/angular/lightbox/lightbox-config.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
Labels: target: major

#1515 build: update version in schematics
  src/angular/schematics/migration.json
  src/angular/schematics/ng-update/index.ts
Labels: target: major

#1512 fix(journey-maps): show "Leit-POIs" for default floor in journey based routing
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/map/map-leit-poi-service.ts
Labels: target: major

#1513 fix(schematics): weaken type check of SchematicsException
  src/angular/schematics/ng-add/setup-project.ts
Labels: target: major

#1501 refactor(angular/button): dynamic icon buttons
  src/angular/button/button.md
  src/angular/button/button.spec.ts
  src/angular/button/button.ts
  src/angular/schematics/ng-update/data/element-selectors.ts
  src/angular/schematics/ng-update/test-cases/v14/icon-button_expected_output.ts
  src/angular/schematics/ng-update/test-cases/v14/icon-button_input.ts
  src/angular/styles/_typography.scss
  src/angular/table/table.md
  src/components-examples/angular/button/button-overview/button-overview-example.html
  src/components-examples/angular/button/icon-button/icon-button-example.html
  src/components-examples/angular/button/icon-button/icon-button-example.ts
  src/components-examples/angular/button/index.ts
  src/components-examples/angular/table/buttons-in-table/buttons-in-table-example.html
  src/components-examples/angular/table/cell-actions-table/cell-actions-table-example.html
  src/showcase/app/shared/component-viewer/example-viewer/example-viewer.component.html
  src/showcase/app/shared/component-viewer/example-viewer/example-viewer.component.scss
Labels: target: major

#1522 build: update Angular version range
  packages.bzl
Labels: target: major

#1523 build: allow absolute import of i18n module
  src/angular/schematics/ng-update/migrations/secondary-entry-points-migration.ts
Labels: target: 13.x

#1516 build: prepare workflows for v14
  .github/workflows/maintenance-tagging-workflow.yml
  renovate.json
Labels: target: major

#1524 build: add integrity check
  .github/workflows/continuous-integration-workflow.yml
  package.json
  src/showcase/assets/stack-blitz/package-lock.json
Labels: target: 14.x

#1514 fix(journey-maps): simplify sort logic
  src/journey-maps/angular/components/level-switch/services/query-map-features.ts
Labels: target: 14.x

#1521 build: set up schematics for version 15
  src/angular/schematics/migration.json
  src/angular/schematics/ng-update/index.ts
Labels: target: 14.x

#1531 chore: fix integrity
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
Labels: target: 14.x

#1533 chore: fix symbols another time
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
Labels: target: 14.x

#1538 build: increase yarn cache version to avoid failing builds
  .github/actions/yarn-install/action.yml
Labels: target: 14.x

#1532 docs(angular/select): improve section about disabling the control, options or groups
  src/angular/select/select.md
Labels: target: 14.x

#1539 ci: add maintenance workflow for changelog
  .github/workflows/maintenance-changelog-workflow.yml
  .github/workflows/maintenance-cherry-pick-workflow.yml
  scripts/update-maintenance-issue.ts
Labels: target: 14.x

#1510 refactor(journey-maps): update MapLibre to V2
  package.json
  src/components-examples/journey-maps/angular/journey-maps-basic/journey-maps-basic-example.css
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.css
  src/journey-maps/angular/BUILD.bazel
  src/journey-maps/angular/angular.md
  src/journey-maps/angular/components/level-switch/services/map-layer-filter.ts
  src/journey-maps/angular/components/marker-details/marker-details.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/services/map/events/features-hover-event.ts
  src/journey-maps/angular/services/map/events/map-cursor-style-event.spec.ts
  src/journey-maps/angular/services/map/events/map-cursor-style-event.ts
  src/journey-maps/angular/services/map/events/map-event-utils.ts
  src/journey-maps/angular/services/map/events/map-selection-event.spec.ts
  src/journey-maps/angular/services/map/map-init-service.ts
  src/journey-maps/angular/services/map/map-marker-service.ts
  src/journey-maps/angular/services/map/map-station-service.ts
  src/journey-maps/angular/testing/maplibre-map-mock.spec.ts
  src/journey-maps/angular/testing/maplibre-map-mock.ts
  src/journey-maps/angular/types.d.ts
  src/journey-maps/package.json
  src/journey-maps/web-component/web-component.md
  tools/postinstall/apply-patches.js
  yarn.lock
Labels: target: 14.x

#1555 fix(angular/tooltip): stop event propagation on trigger click
  src/angular/tooltip/tooltip.spec.ts
  src/angular/tooltip/tooltip.ts
Labels: target: 14.x

#1551 ci: run changelog workflow only if a new tag was created
  .github/workflows/maintenance-changelog-workflow.yml
Labels: target: 14.x

#1556 docs: update stackblitz tsconfig.json
  src/showcase/assets/stack-blitz/tsconfig.json
Labels: target: 14.x

#1552 fix(angular/processflow): accept AbstractControl in isErrorState
  src/angular/core/common-behaviors/error-state.ts
  src/angular/processflow/processflow.ts
Labels: target: 14.x

#1553 docs: update CONTRIBUTING.md
  CODING_STANDARDS.md
  CONTRIBUTING.md
Labels: target: 14.x

#1561 feat(angular/notification): add type `info-light`
  src/angular/notification/notification.scss
  src/angular/notification/notification.spec.ts
  src/angular/notification/notification.ts
  src/components-examples/angular/notification/simple-notification/simple-notification-example.html
Labels: target: 14.x

#1546 fix(multiple): style changes for better accessibility
  src/angular/accordion/expansion-panel.scss
  src/angular/chips/chips.scss
  src/angular/input/input.spec.ts
  src/angular/notification/notification.scss
  src/angular/notification/notification.spec.ts
  src/angular/status/status.html
  src/angular/status/status.scss
  src/angular/status/status.spec.ts
  src/angular/styles/_typography.scss
  src/components-examples/angular/autocomplete/autocomplete-option-group/autocomplete-option-group-example.html
  src/components-examples/angular/icon/icon-fit/icon-fit-example.html
  src/components-examples/angular/icon/icon-fit/icon-fit-example.ts
  src/components-examples/angular/icon/index.ts
  src/components-examples/angular/search/search-simple-reactive-forms/search-simple-reactive-forms-example.html
Labels: target: 14.x
