Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-04, with the labels that each got.

#1849 build: update dependency build_bazel_rules_nodejs to v5.8.2
  WORKSPACE
Labels: target: 15.x, preview-available

#1856 chore: update typescript to 5.0.2
  package.json
  src/angular/form-field/form-field.html
  src/angular/schematics/ng-update/index.ts
  src/angular/schematics/ng-update/migrations/secondary-entry-points-migration.ts
  src/showcase/app/app.component.html
  tools/tslint-rules/lifecycleHookInterfaceRule.ts
  tools/tslint-rules/requirePropertyTypedefRule.ts
  tslint.json
  yarn.lock
Labels: preview-available

#1869 fix(angular/datepicker): avoid calendar being cut off on small screens
  src/angular/datepicker/datepicker-content/datepicker-content.scss
  src/angular/datepicker/datepicker/datepicker.ts
Labels: target: 15.x, preview-available

#1874 fix: make rxjs imports forward compatible
  src/angular/lightbox/lightbox-container.ts
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
Labels: target: 15.x, preview-available

#1875 chore: update to angular 16.0.0-rc.1
  package.json
  src/angular/datepicker/BUILD.bazel
  src/angular/datepicker/datepicker/datepicker.spec.ts
  tools/angular/esbuild.config.mjs
  tools/angular/index.bzl
  yarn.lock
Labels: target: major, preview-available

#1865 feat(journey-maps): journey start- and end-station clickable
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/journey/zh-be_wyleregg.ts
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/journey/zh-sh_waldfriedhof.ts
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/routes/biel-lyss.ts
  src/journey-maps/angular/services/map/map-station-service.ts
Labels: target: 15.x, preview-available

#1877 chore(journey-maps): remove sebisteiner from journey-maps code owners
  .github/CODEOWNERS
Labels: target: 15.x

#1879 build: fix build dependencies
  package.json
Labels: target: 15.x, preview-available

#1876 build: update tooling to generate APF version 16 packages
  WORKSPACE
  angular-tsconfig.json
  package.json
  scripts/build.ts
  src/bazel-tsconfig-build.json
  tools/angular/esbuild.config.mjs
  tools/defaults.bzl
  tools/postinstall/apply-patches.js
  tools/postinstall/devmode-es2020-bazel.patch
  tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
  tools/postinstall/patches/@bazel+concatjs+5.8.1.patch
  tsconfig.json
  yarn.lock
Labels: target: major, preview-available

#1881 build: lint BUILD.bazel files
  src/journey-maps/web-component/BUILD.bazel
  src/showcase/BUILD.bazel
Labels: target: 15.x, preview-available

#1866 fix(angular/datepicker): remove div as a child of button
  src/angular/datepicker/calendar-body/calendar-body.html
Labels: target: 15.x

#1882 build: update node to v18
  .nvmrc
  WORKSPACE
  package.json
  renovate.json
  yarn.lock
Labels: target: 15.x

#1873 fix(journey-maps): fix multiline attribution style
  src/journey-maps/angular/BUILD.bazel
  src/journey-maps/angular/components/attribution/attribution.html
  src/journey-maps/angular/components/attribution/attribution.scss
  src/journey-maps/angular/components/attribution/attribution.ts
Labels: target: 15.x, preview-available
