Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-08, with the labels that each got.

#1951 feat(journey-maps): provide mock data with indoor transfer
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/journey/zh-be_wyleregg.ts
Labels: preview-available, target: 16.x

#1959 feat(journey-maps): prohibit simultaneous selection of sbb marker and poi
  src/journey-maps/angular/components/feature-event-listener/feature-event-listener.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/map/events/map-selection-event.ts
  src/journey-maps/angular/services/map/map-marker-service.ts
  src/journey-maps/angular/services/map/marker-or-poi-selection-state.service.ts
  src/journey-maps/angular/services/map/util/poi-details.ts
Labels: preview-available, target: 16.x

#1960 feat(journey-maps): removed indoor pois in examples
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/transfer/bern-indoor.ts
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/transfer/geneve-indoor.ts
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/transfer/zurich-indoor.ts
Labels: preview-available, target: 16.x

#1963 fix(journey-maps): prevent error when unselecting POIs without previously selecting any
  src/journey-maps/angular/components/feature-event-listener/feature-event-listener.ts
Labels: preview-available, target: 16.x

#1948 feat(journey-maps): add web-component examples page
  src/journey-maps/web-component/BUILD.bazel
  src/journey-maps/web-component/web-component-api.md
  src/journey-maps/web-component/web-component-examples.md
  src/showcase/app/journey-maps/journey-maps-routing.module.ts
Labels: preview-available, target: 16.x

#1966 cdi, NOJIRA - allow deselecting pois even without popups
  src/journey-maps/angular/components/feature-event-listener/feature-event-listener.ts
  src/journey-maps/angular/journey-maps.html
  src/journey-maps/angular/journey-maps.ts
Labels: preview-available, target: 16.x

#1965 feat(angular/autocomplete): don't assign to model value while typing …
  src/angular/autocomplete/autocomplete-trigger.ts
  src/angular/autocomplete/autocomplete.spec.ts
  src/components-examples/angular/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.html
  src/components-examples/angular/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
Labels: preview-available, target: 16.x

#1964 feat(angular/dialog): expose rendered ComponentRef
  src/angular/dialog/dialog-ref.ts
  src/angular/dialog/dialog.spec.ts
  src/angular/dialog/dialog.ts
  src/angular/lightbox/lightbox.spec.ts
Labels: preview-available, target: 16.x

#1973 fix(angular/dialog): update aria-labelledby if title is swapped
  src/angular/dialog/dialog-container.ts
  src/angular/dialog/dialog-content-directives.ts
  src/angular/dialog/dialog.spec.ts
  src/angular/lightbox/lightbox-container.ts
Labels: target: 16.x

#1974 build: update xlf files
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
Labels: preview-available, target: 16.x

#1978 feat(multiple): add dark mode variant
  src/angular/core/common-behaviors/variant.ts
  src/showcase/app/app.component.html
  src/showcase/app/variant-switch.ts
Labels: preview-available

#1981 feat(angular/accordion): implement dark mode
  src/angular/accordion/expansion-panel-header.html
  src/angular/accordion/expansion-panel.scss
  src/angular/sidebar/sidebar/sidebar.scss
  src/angular/styles/_typography.scss
Labels: preview-available

#1980 feat(angular/sidebar): implement dark mode
  src/angular/accordion/expansion-panel-header.html
  src/angular/accordion/expansion-panel.scss
  src/angular/core/common-behaviors/variant.ts
  src/angular/sidebar/icon-sidebar/icon-sidebar.scss
  src/angular/sidebar/sidebar/sidebar.scss
  src/angular/styles/_mixins.scss
  src/angular/styles/_typography.scss
  src/angular/styles/_variables.scss
  src/showcase/app/app.component.html
  src/showcase/app/variant-switch.ts
Labels: preview-available

#1985 feat(angular/badge): implement dark mode
  src/angular/styles/_typography.scss
Labels: preview-available
