Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-11, with the labels that each got.

#2064 feat: dark mode for datepicker
  src/angular/datepicker/calendar/calendar.scss
  src/angular/styles/_typography.scss
Labels: preview-available

#2065 feat(multiple): dark mode for checkbox panel und radiobutton panel
  src/angular/styles/_typography.scss
Labels: preview-available

#2067 chore(angular/table): dark mode
  src/angular/styles/_typography.scss
  src/angular/table/sort/sort-header.scss
Labels: preview-available

#2004 fix(multiple): remove obsolete base classes
  src/angular/autocomplete/autocomplete.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
  src/angular/tabs/public-api.ts
  src/angular/tabs/tab-body.ts
  src/angular/tabs/tab-group.ts
  src/angular/tabs/tab-header.ts
  src/angular/tooltip/tooltip.ts
Labels: preview-available, target: 16.x

#2043 refactor: autodetect dark mode
  src/angular/core/common-behaviors/common.module.ts
  src/angular/core/common-behaviors/variant.ts
  src/angular/notification/notification.html
  src/angular/styles/_typography.scss
  src/angular/typography.md
  src/showcase/app/app.component.html
  src/showcase/app/app.component.ts
  src/showcase/app/variant-switch.ts
  src/showcase/styles.scss
Labels: preview-available

#1983 feat(multiple): implement dark mode
  package.json
  src/angular/accordion/expansion-panel-header.html
  src/angular/accordion/expansion-panel.scss
  src/angular/breadcrumb/breadcrumbs.scss
  src/angular/chips/chips.scss
  src/angular/core/common-behaviors/common.module.ts
  src/angular/datepicker/calendar/calendar.scss
  src/angular/dialog/dialog.scss
  src/angular/header-lean/header.scss
  src/angular/menu/menu.scss
  src/angular/notification-toast/notification-toast-container.scss
  src/angular/notification/notification.html
  src/angular/notification/notification.scss
  src/angular/processflow/processflow.scss
  src/angular/processflow/step-header.scss
  src/angular/select/select.html
  src/angular/select/select.scss
  src/angular/sidebar/icon-sidebar/icon-sidebar.scss
  src/angular/sidebar/sidebar/sidebar.scss
  src/angular/status/status.scss
  src/angular/styles/_mixins.scss
  src/angular/styles/_typography.scss
  src/angular/styles/_variables.scss
  src/angular/table/sort/sort-header.scss
  src/angular/tabs/_tabs.scss
  src/angular/tag/tag.scss
  src/angular/textarea/textarea/textarea.scss
  src/angular/textexpand/textexpand.scss
  src/angular/toggle/toggle.scss
  src/angular/tooltip/tooltip.scss
  src/angular/typography.md
  src/angular/usermenu/usermenu.scss
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.scss
  src/showcase/app/app.component.html
  src/showcase/app/app.component.scss
  src/showcase/app/app.component.ts
  src/showcase/app/introduction/introduction.component.scss
  src/showcase/app/variant-switch.ts
  src/showcase/styles.scss
  yarn.lock
Labels: target: major, preview-available

#2070 chore: prepare v17 release
  packages.bzl
  src/showcase/app/howtoupdate/update-steps.ts
  src/showcase/assets/stack-blitz/package.json
Labels: target: major

#2071 ci: update target branch for tagging workflow
  .github/workflows/maintenance-tagging.yml
Labels: preview-available, target: 17.x

#2082 ci: make 17.x a renovate base branch
  renovate.json
Labels: preview-available, target: 17.x

#2081 fix(multiple): change dark mode background to midnight and fix some styles
  src/angular/datepicker/calendar/calendar.scss
  src/angular/datepicker/datepicker-content/datepicker-content.scss
  src/angular/dialog/dialog.scss
  src/angular/file-selector/file-selector.scss
  src/angular/header-lean/header-menu-trigger.scss
  src/angular/header-lean/header.scss
  src/angular/lightbox/lightbox.scss
  src/angular/menu/menu.scss
  src/angular/sidebar/icon-sidebar/icon-sidebar.scss
  src/angular/sidebar/sidebar/sidebar.scss
  src/angular/styles/_typography.scss
  src/angular/tooltip/tooltip.scss
  src/showcase/app/variant-switch.ts
Labels: preview-available, target: 16.x

#2090 chore: fix disabled radio button and checkbox style
  src/angular/styles/_typography.scss
Labels: preview-available, target: 17.x

#2095 feat(journey-maps): migrate to maplibre 3.6.1
  package.json
  src/components-examples/journey-maps/angular/journey-maps-basic/journey-maps-basic-example.css
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.css
  src/journey-maps/angular/angular.md
  src/journey-maps/angular/controls/sbbGeolocateControl.ts
  src/journey-maps/angular/services/map/events/map-event-utils.ts
  src/journey-maps/angular/services/map/events/route-utils.ts
  yarn.lock
Labels: preview-available, target: 17.x

#2093 fix(journey-maps): prevent console errors
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/journey-maps/angular/components/level-switch/services/level-switcher.ts
  src/journey-maps/angular/components/level-switch/services/map-layer-filter.ts
Labels: preview-available, target: 17.x

#2099 fix(angular/input): change border color to smoke
  src/angular/styles/_typography.scss
Labels: preview-available, target: 17.x

#2097 fix(angular/sidebar): change dark mode background to charcoal
  src/angular/styles/_typography.scss
Labels: preview-available, target: 17.x

#2101 fix(showcase): make expandable table example working on all browsers
  src/components-examples/angular/table/expandable-table/expandable-table-example.html
Labels: preview-available, target: 17.x

#2103 fix(angular/sidebar): darker hover color for sidebar items in dark mode
  src/angular/sidebar/sidebar/sidebar.scss
  src/angular/styles/_typography.scss
Labels: preview-available, target: 17.x
