Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-06, with the labels that each got.

#1899 feat(journey-maps): extend poi-url-generation with preview flag
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/map/map-init-service.ts
  src/journey-maps/angular/services/map/map-url-service.ts
Labels: target: 15.x, preview-available, target: 16.x

#1917 chore: update library version in main branch
  package.json
Labels: target: major

#1925 build: remove `BundlingTypes` strategy to find out if it's still needed
  .bazelrc
Labels: preview-available, target: 16.x

#1913 docs(journey-maps): improve the web-component docs
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/web-component/web-component.md
Labels: preview-available, target: 16.x

#1928 feat(journey-maps): bind method for web component
  src/journey-maps/angular/journey-maps.ts
Labels: preview-available, target: 16.x
