Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-05, with the labels that each got.

#1898 chore: prepare the 16 release
  packages.bzl
  renovate.json
  src/showcase/app/howtoupdate/update-steps.ts
  src/showcase/assets/stack-blitz/package-lock.json
  src/showcase/assets/stack-blitz/package.json
Labels: preview-available

#1900 ci: update label of tagging workflow to "16.x"
  .github/workflows/maintenance-tagging.yml
Labels: target: 16.x

#1883 docs(journey-maps): document how to configure listenerOptions
  src/journey-maps/web-component/web-component.md
Labels: preview-available, target: 16.x

#1889 feat(angular/icon): update to new icons and pictograms
  src/angular/icon/icon-registry.ts
  src/angular/icon/icon.spec.ts
  src/angular/icon/icon.ts
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-dialog/cdn-icon-dialog.component.ts
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-list.component.html
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-list.component.ts
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.html
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.scss
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.ts
  src/showcase/app/angular/icon-overview/cdn-icon.service.ts
  src/showcase/app/angular/icon-overview/icon-overview.component.ts
Labels: preview-available, target: 16.x

#1903 build: fix preview image cleanup
  .github/workflows/preview-image-cleanup.yml
Labels: preview-available, target: 16.x
