Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-02, with the labels that each got.

#1806 build: update angular shared dev-infra code
  .github/actions/yarn-install/action.yml
  WORKSPACE
  package.json
  packages.bzl
  scripts/build.ts
  tools/angular/BUILD.bazel
  tools/angular/esbuild.config.mjs
  yarn.lock
Labels: target: 15.x, preview-available

#1807 feat(journeyMaps): implement bbox event emitter
  src/journey-maps/angular/journey-maps.ts
Labels: target: 15.x, preview-available

#1810 ci: fix publishing of npm package
  packages.bzl
Labels: target: 15.x

#1812 chore(deps): bump @angular/bazel to 15.0.4
  package.json
  renovate.json
  yarn.lock
Labels: target: 15.x, preview-available

#1811 feat(journey-maps): use the new aerial style 'aerial_sbb_ki_v2'
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/journey-maps/angular/components/feature-event-listener/feature-event-listener.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/map/map-marker-service.ts
  src/journey-maps/angular/services/map/map-station-service.ts
  src/journey-maps/angular/services/map/map-transfer-service.ts
Labels: target: 15.x, preview-available

#1814 feat(journey-maps): switch between 2D and 3D layers
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
  src/journey-maps/angular/components/level-switch/services/level-switcher.ts
  src/journey-maps/angular/components/level-switch/services/query-map-features.ts
  src/journey-maps/angular/journey-maps.ts
Labels: target: 15.x, preview-available

#1823 fix: ensure correct bundling of showcase
  packages.bzl
Labels: target: 15.x, preview-available

#1825 docs: make environment banner text configurable
  Dockerfile
  docker-compose.yml
  src/showcase/BUILD.bazel
  src/showcase/app/app.component.html
  src/showcase/app/app.component.ts
Labels: target: 15.x, preview-available

#1828 feat(journey-maps): improved route hover
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/journey-maps/angular/services/map/map-routes.service.ts
Labels: target: 15.x, preview-available

#1830 chore(deps): update angular to v15.2.0 (main)
  package.json
  src/angular/dialog/dialog.ts
  yarn.lock
Labels: target: 15.x, preview-available

#1831 chore(deps): update angular to v15.2.0 (15.x)
  package.json
  src/angular/dialog/dialog.ts
  yarn.lock
Labels: preview-available

#1787 feat(angular/datepicker): add option to prevent entering overflowing dates
  src/angular/core/datetime/datepicker-token.ts
  src/angular/core/datetime/lean-date-adapter.spec.ts
  src/angular/core/datetime/lean-date-adapter.ts
  src/angular/core/datetime/native-date-adapter.ts
  src/angular/datepicker/datepicker.md
  src/angular/datepicker/datepicker/datepicker.spec.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
Labels: target: 15.x, preview-available
