Repository sbb-design-systems/sbb-angular, pull requests merged in 2023-01, with the labels that each got.

#1765 feat(journey-maps): add new POIs subcategories
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/web-component/showcase.ts
Labels: target: 15.x

#1766 feat(journey-maps): add new POIs subcategories for angular showcase a…
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
Labels: target: 15.x

#1770 chore(deps): update renovate.json
  renovate.json
Labels: target: 15.x

#1771 chore(deps): ignore `@types/yargs` in renovate.json
  renovate.json
Labels: target: 15.x

#1767 fix(journey-maps): export web component CSS in package.json
  src/journey-maps/package.json
Labels: target: 15.x

#1778 build: bump year
  LICENSE
Labels: target: 15.x

#1780 build: update typescript to 4.9 and angular to 15.1
  package.json
  yarn.lock
Labels: target: 15.x

#1779 test(angular/menu): ensure aria-expanded is updating in an OnPush component
  src/angular/menu/menu-trigger.ts
  src/angular/menu/menu.spec.ts
Labels: target: 15.x

#1777 build: update to latest version of parse5
  package.json
  src/angular-experimental/schematics/BUILD.bazel
  src/angular/schematics/BUILD.bazel
  src/angular/schematics/utils.ts
  yarn.lock
Labels: target: 15.x

#1769 feat(journey-maps): switch to map style 'ki_v2'
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.html
  src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/journey/zh-be_wyleregg.ts
  src/components-examples/journey-maps/angular/journey-maps-full/mock-response/journey/zh-sh_waldfriedhof.ts
  src/journey-maps/angular/components/level-switch/services/level-switcher.ts
  src/journey-maps/angular/components/level-switch/services/map-layer-filter.ts
  src/journey-maps/angular/components/level-switch/services/query-map-features.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/constants.ts
  src/journey-maps/angular/services/map/events/map-event-utils.ts
  src/journey-maps/angular/services/map/events/map-selection-event.ts
  src/journey-maps/angular/services/map/map-init-service.ts
  src/journey-maps/angular/services/map/map-journey-service.ts
  src/journey-maps/angular/services/map/map-marker-service.ts
  src/journey-maps/angular/services/map/map-route-service.ts
  src/journey-maps/angular/services/map/map-routes.service.ts
  src/journey-maps/angular/services/map/map-service.ts
  src/journey-maps/angular/services/map/map-station-service.ts
  src/journey-maps/angular/services/map/map-transfer-service.ts
  src/journey-maps/angular/services/map/map-zone-service.ts
  src/journey-maps/angular/services/map/util/array-utils.spec.ts
  src/journey-maps/angular/services/map/util/array-utils.ts
  src/journey-maps/angular/services/map/util/feature-collection-util.ts
  src/journey-maps/angular/services/map/util/style-version-lookup.ts
  src/journey-maps/angular/services/map/util/walk-floor-updater.ts
  src/journey-maps/angular/util/input-validation.spec.ts
  src/journey-maps/angular/util/input-validation.ts
Labels: target: 15.x

#1792 docs(loading-indicator): add note about fullbox mode
  src/angular/loading-indicator/loading-indicator.md
Labels: target: 15.x

#1793 ci: add label after preview docker image was published
  .github/workflows/continuous-integration.yml
  .github/workflows/preview-deployment.yml
Labels: target: 15.x

#1794 ci: specify pr number when adding 'preview-available' label
  .github/workflows/preview-deployment.yml
Labels: target: 15.x

#1795 fix: remove engine entries in package.json
  src/angular-experimental/package.json
  src/angular-maps/package.json
  src/angular/package.json
  src/journey-maps/package.json
Labels: target: 13.x, target: 14.x, target: 15.x

#1800 docs: update changelog
  CHANGELOG.md
Labels: target: 15.x, preview-available

#1804 fix(angular/dialog): scrollable content if no dialog height is defined
  src/angular/dialog/dialog.scss
Labels: target: 15.x, preview-available
