Repository sbb-design-systems/sbb-angular, pull requests merged in 2024-10, with the labels that each got.

#2395 test: remove compileComponent calls
  src/angular/accordion/accordion.spec.ts
  src/angular/accordion/expansion-panel.spec.ts
  src/angular/alert/alert.spec.ts
  src/angular/autocomplete/autocomplete.spec.ts
  src/angular/autocomplete/autocomplete.zone.spec.ts
  src/angular/breadcrumb/breadcrumbs.spec.ts
  src/angular/button/button.spec.ts
  src/angular/checkbox-panel/checkbox-panel.spec.ts
  src/angular/checkbox/checkbox.spec.ts
  src/angular/chips/chip-input.spec.ts
  src/angular/chips/chip-list.spec.ts
  src/angular/chips/chip-remove.spec.ts
  src/angular/core/option/option.spec.ts
  src/angular/datepicker/calendar/calendar-header.spec.ts
  src/angular/datepicker/calendar/calendar.spec.ts
  src/angular/datepicker/month-view/month-view.spec.ts
  src/angular/dialog/dialog.spec.ts
  src/angular/dialog/dialog.zone.spec.ts
  src/angular/file-selector/file-selector.spec.ts
  src/angular/header-lean/header.spec.ts
  src/angular/i18n/sbb-ch-patch.spec.ts
  src/angular/icon/icon.spec.ts
  src/angular/input/input.spec.ts
  src/angular/lightbox/lightbox.spec.ts
  src/angular/lightbox/lightbox.zone.spec.ts
  src/angular/menu/menu.spec.ts
  src/angular/notification-toast/notification-toast.spec.ts
  src/angular/notification-toast/notification-toast.zone.spec.ts
  src/angular/notification/notification.spec.ts
  src/angular/pagination/navigation/navigation.spec.ts
  src/angular/pagination/paginator/paginator.spec.ts
  src/angular/processflow/processflow.spec.ts
  src/angular/radio-button-panel/radio-button-panel.spec.ts
  src/angular/search/search.spec.ts
  src/angular/select/select.spec.ts
  src/angular/sidebar/icon-sidebar/icon-sidebar.spec.ts
  src/angular/sidebar/sidebar/sidebar.spec.ts
  src/angular/status/status.spec.ts
  src/angular/table/sort/sort.spec.ts
  src/angular/table/table.spec.ts
  src/angular/table/table/table-data-source.spec.ts
  src/angular/tabs/tab-body.spec.ts
  src/angular/tabs/tab-group.spec.ts
  src/angular/tabs/tab-header.spec.ts
  src/angular/tabs/tab-nav-bar.spec.ts
  src/angular/tag/tags.spec.ts
  src/angular/toggle/toggle.spec.ts
  src/angular/tooltip/tooltip-wrapper.spec.ts
  src/angular/tooltip/tooltip.zone.spec.ts
  src/angular/usermenu/usermenu.spec.ts
  src/journey-maps/angular/components/leit-poi/leit-poi.spec.ts
  src/journey-maps/angular/components/level-switch/services/level-switcher.spec.ts
  src/journey-maps/angular/journey-maps.spec.ts
Labels: angular-components-sync, target: 18.x

#2394 refactor(angular/input): support signal-based input accessor
  src/angular/input/input-value-accessor.ts
  src/angular/input/input.ts
Labels: angular-components-sync, target: 18.x

#2393 fix(angular/tooltip): correct icon styling when placed inside label
  src/angular/form-field/form-field.scss
Labels: target: 18.x

#2346 feat(journey-maps): new input field for journey-routes data
  src/components-examples/journey-maps/angular/journey-maps-routes-zones/journey-maps-routes-zones-example.html
  src/components-examples/journey-maps/angular/journey-maps-routes-zones/journey-maps-routes-zones-example.ts
  src/components-examples/journey-maps/angular/shared/transfer/bern-indoor.ts
  src/components-examples/journey-maps/angular/shared/transfer/geneve-indoor.ts
  src/components-examples/journey-maps/angular/shared/transfer/luzern4-j.ts
  src/components-examples/journey-maps/angular/shared/transfer/zurich-indoor.ts
  src/components-examples/journey-maps/angular/shared/trip/be-sh.ts
  src/components-examples/journey-maps/angular/shared/trip/zh-be_wyleregg.ts
  src/components-examples/journey-maps/angular/shared/trip/zh-sh_waldfriedhof.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/map/map-journey-service.ts
  src/journey-maps/angular/util/input-validation.spec.ts
  src/journey-maps/angular/util/input-validation.ts
Labels: target: 18.x

#2406 refactor(angular/core): convert to standalone
  src/angular/core/option/optgroup.ts
  src/angular/core/option/option-hint.ts
  src/angular/core/option/option.module.ts
  src/angular/core/option/option.ts
  src/angular/core/option/pseudo-checkbox.ts
  src/angular/radio-button/radio-button.ts
  src/angular/sidebar/sidebar-base.ts
Labels: target: 18.x

#2405 build: update to latest Angular next version
  package.json
  packages.bzl
  src/angular/autocomplete/autocomplete.spec.ts
  src/angular/autocomplete/autocomplete.zone.spec.ts
  src/angular/chips/chip-input.spec.ts
  src/angular/core/option/option.spec.ts
  src/angular/dialog/dialog.spec.ts
  src/angular/i18n/sbb-ch-patch.spec.ts
  src/angular/icon/icon.spec.ts
  src/angular/menu/menu.spec.ts
  src/angular/notification-toast/notification-toast.spec.ts
  src/angular/schematics/ng-update/index.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
  src/angular/schematics/ng-update/migrations/secondary-entry-points-migration.ts
  src/angular/select/select.spec.ts
  src/angular/tooltip/tooltip.spec.ts
  src/components-examples/angular/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
  src/components-examples/angular/sidebar/collapsible-sidebar/collapsible-sidebar-example.ts
  src/components-examples/angular/sidebar/multiple-sidebars/multiple-sidebars-example.ts
  src/components-examples/journey-maps/angular/journey-maps-pois-markers/journey-maps-pois-markers-example.ts
  src/components-examples/journey-maps/angular/journey-maps-routes-zones/journey-maps-routes-zones-example.ts
  src/components-examples/journey-maps/angular/journey-maps-ui-options/journey-maps-ui-options-example.ts
  src/journey-maps/angular/components/attribution/attribution.ts
  src/journey-maps/angular/components/basemap-switch/basemap-switch.ts
  src/journey-maps/angular/components/feature-event-listener/feature-event-listener.ts
  src/journey-maps/angular/components/geolocate-button/geolocate-button.ts
  src/journey-maps/angular/components/home-button/home-button.ts
  src/journey-maps/angular/components/leit-poi/leit-poi.ts
  src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
  src/journey-maps/angular/components/level-switch/level-switch.ts
  src/journey-maps/angular/components/marker-details/marker-details.ts
  src/journey-maps/angular/components/overlay-paginator/overlay-paginator.ts
  src/journey-maps/angular/components/popup/popup.ts
  src/journey-maps/angular/components/teaser/teaser.ts
  src/journey-maps/angular/components/zoom-controls/zoom-controls.ts
  src/journey-maps/angular/directives/template-outlet.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/esri-plugin/esri-plugin.ts
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-dialog/cdn-icon-dialog.component.ts
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-list.component.ts
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon/cdn-icon.component.ts
  src/showcase/app/angular/icon-overview/icon-overview.component.ts
  src/showcase/app/app.component.ts
  src/showcase/app/howtoupdate/how-to-update.component.ts
  src/showcase/app/introduction/introduction.component.ts
  src/showcase/app/shared/component-viewer/component-viewer/component-viewer.component.ts
  src/showcase/app/shared/component-viewer/example-list-viewer/example-list-viewer.component.ts
  src/showcase/app/shared/component-viewer/example-viewer/example-viewer.component.ts
  src/showcase/app/shared/component-viewer/html-viewer/html-viewer.component.ts
  src/showcase/app/shared/component-viewer/stack-blitz/stack-blitz-button.ts
  src/showcase/app/shared/component-viewer/variant-limitation-component/variant-limitation.component.ts
  src/showcase/app/shared/markdown-viewer/markdown-viewer.component.ts
  src/showcase/app/shared/mode-notification-toast/mode-notification-toast.component.ts
  src/showcase/app/shared/package-viewer/package-viewer.component.ts
  yarn.lock
Labels: target: major
