Repository sbb-design-systems/sbb-angular, pull requests merged in 2024-05, with the labels that each got.

#2247 Revert "fix(angular/tabs): use ResizeObserver to react to size changes (#2234)"
  src/angular/tabs/paginated-tab-header.ts
  src/angular/tabs/tab-header.spec.ts
  tslint.json
Labels: preview-available, target: 17.x

#2233 refactor(angular/menu): remove use of zone onStable to focus items
  src/angular/menu/menu.spec.ts
  src/angular/menu/menu.ts
Labels: target: major, preview-available

#2218 refactor(angular/tooltip): remove use of zone onStable for overlay positioning
  src/angular/tooltip/tooltip.ts
Labels: target: major, preview-available

#2245 fix(angular/file-selector): allow disabling multiple mode
  src/angular/file-selector/file-selector.html
  src/angular/file-selector/file-selector.spec.ts
Labels: preview-available, target: 17.x

#2246 fix(angular/badge): fix badge positioning on icon
  src/angular/badge/badge.md
  src/angular/styles/_typography.scss
  src/components-examples/angular/badge/BUILD.bazel
  src/components-examples/angular/badge/badge-overview/badge-overview-example.html
  src/components-examples/angular/badge/badge-overview/badge-overview-example.ts
Labels: preview-available, target: 17.x

#2258 fix(multiple): remove label for attribute on non-native elements
  src/angular/form-field/form-field-control.ts
  src/angular/form-field/form-field.html
  src/angular/select/select.ts
  src/angular/textarea/textarea/textarea.ts
Labels: preview-available, target: 17.x

#2257 fix(angular/dialog): mark dialog content as scrollable
  src/angular/dialog/dialog-content-directives.ts
  src/angular/dialog/dialog.spec.ts
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
Labels: preview-available, target: 17.x

#2255 fix(angular/menu): remove dependency on NgClass
  src/angular/menu/menu.html
  src/angular/menu/menu.ts
Labels: preview-available, target: 17.x

#2254 fix(angular/autocomplete): remove dependency on NgClass
  src/angular/autocomplete/autocomplete.html
  src/angular/autocomplete/autocomplete.ts
Labels: preview-available, target: 17.x

#2251 fix(angular/tabs): remove dependency on NgClass
  src/angular/tabs/tab-group.html
  src/angular/tabs/tab-group.ts
  src/angular/tabs/tab.ts
Labels: preview-available, target: 17.x

#2253 fix(angular/datepicker): remove dependency on NgClass
  src/angular/datepicker/calendar-body/calendar-body.html
  src/angular/datepicker/calendar-body/calendar-body.ts
  src/angular/datepicker/datepicker-content/datepicker-content.html
  src/angular/datepicker/datepicker-content/datepicker-content.ts
  src/angular/datepicker/datepicker/datepicker.ts
Labels: preview-available, target: 17.x

#2261 build: convert build scripts to ESM
  .github/workflows/continuous-integration.yml
  package.json
  scripts/build.mts
  scripts/cache.mts
  scripts/tsconfig.json
  scripts/update-icon-names.mts
  yarn.lock
Labels: preview-available, target: 17.x

#2266 chore: fix hot-reloading
  package.json
Labels: preview-available, target: 17.x

#2267 ci: fix angular-components-sync
  .github/workflows/angular-components-sync.yml
  scripts/angular-components-sync-test.mts
  scripts/angular-components-sync.mts
Labels: preview-available, target: 17.x

#2268 fix(angular/tooltip): tooltip should mark for check when visibility changes
  src/angular/tooltip/tooltip.ts
Labels: preview-available, target: 17.x, angular-components-sync

#2270 fix(angular/chips): simplify repeat chip removal prevention
  src/angular/chips/chip-input.ts
  src/angular/chips/chip-list.spec.ts
  src/angular/chips/chip.ts
Labels: target: 17.x, angular-components-sync

#2269 fix(angular/datepicker): resolve repeater warnings in calendar
  src/angular/datepicker/calendar-body/calendar-body.html
  src/angular/datepicker/calendar-body/calendar-body.ts
  src/angular/datepicker/month-view/month-view.html
Labels: target: major, preview-available, angular-components-sync

#2278 ci: prepare update to angular 18
  .github/workflows/maintenance-tagging.yml
  packages.bzl
  renovate.json
  src/showcase/app/howtoupdate/update-steps.ts
  src/showcase/app/shared/component-viewer/stack-blitz/stack-blitz-writer.ts
  src/showcase/assets/stack-blitz/angular.json
  src/showcase/assets/stack-blitz/package.json
  src/showcase/assets/stack-blitz/src/styles.css
Labels: preview-available, target: 18.x

#2280 fix: update schematics for v18
  RELEASE.md
  src/angular/schematics/migration.json
  src/angular/schematics/ng-update/index.ts
Labels: target: 18.x

#2281 ci: fix maintenance workflow
  .github/workflows/maintenance-changelog.yml
  .github/workflows/maintenance-cherry-pick.yml
  scripts/update-maintenance-issue.mts
Labels: preview-available, target: 18.x

#2284 docs: update links to digital.sbb.ch
  src/showcase/app/introduction/introduction.component.html
Labels: preview-available, target: 18.x
