Repository sbb-design-systems/sbb-angular, pull requests merged in 2024-11, with the labels that each got.

#2409 feat(journey-maps): new option to set the display of POIs as round icons
  src/components-examples/journey-maps/angular/journey-maps-pois-markers/journey-maps-pois-markers-example.html
  src/components-examples/journey-maps/angular/journey-maps-pois-markers/journey-maps-pois-markers-example.ts
  src/journey-maps/angular/components/feature-event-listener/feature-event-listener.ts
  src/journey-maps/angular/journey-maps.interfaces.ts
  src/journey-maps/angular/journey-maps.ts
  src/journey-maps/angular/services/constants.ts
  src/journey-maps/angular/services/map/map-poi-service.ts
Labels: target: 18.x

#2412 test(angular/table): fix table tests after CDK update
  package.json
  src/angular/table/table.spec.ts
  yarn.lock
Labels: target: 18.x

#2413 refactor(multiple): migrate more components to the inject function
  src/angular/accordion/expansion-panel-content.ts
  src/angular/accordion/expansion-panel-header.ts
  src/angular/accordion/expansion-panel.ts
  src/angular/autocomplete/autocomplete-origin.ts
  src/angular/dialog/BUILD.bazel
  src/angular/dialog/dialog-container.ts
  src/angular/dialog/dialog-content-directives.ts
  src/angular/dialog/dialog.spec.ts
  src/angular/dialog/dialog.ts
  src/angular/dialog/dialog.zone.spec.ts
  src/angular/header-lean/app-chooser-section.ts
  src/angular/header-lean/header-directives.ts
  src/angular/header-lean/header-menu-item.ts
  src/angular/header-lean/header-menu-trigger.ts
  src/angular/header-lean/header-menu.ts
  src/angular/header-lean/header.ts
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
  src/angular/lightbox/BUILD.bazel
  src/angular/lightbox/lightbox-container.ts
  src/angular/lightbox/lightbox-content-directives.ts
  src/angular/lightbox/lightbox.spec.ts
  src/angular/lightbox/lightbox.ts
  src/angular/lightbox/lightbox.zone.spec.ts
  src/angular/processflow/processflow.spec.ts
  src/angular/processflow/processflow.ts
  src/angular/processflow/step-content.ts
  src/angular/processflow/step-header.ts
  src/angular/search/search.spec.ts
  src/angular/search/search.ts
  src/angular/select/select.spec.ts
  src/angular/select/select.ts
  src/angular/sidebar/icon-sidebar/icon-sidebar.ts
  src/angular/sidebar/sidebar-base.ts
  src/angular/sidebar/sidebar/sidebar.ts
Labels: target: major

#2414 refactor(angular/tabs): remove unnecessary base classes
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
  src/angular/tabs/public-api.ts
  src/angular/tabs/tab-nav-bar.ts
Labels: target: major, angular-components-sync

#2417 fix(angular/tabs): remove IE animation workaround
  src/angular/tabs/tab-body.ts
Labels: angular-components-sync, target: 18.x

#2416 refactor(multiple): remove CommonModule imports
  src/angular/accordion/accordion.module.ts
  src/angular/autocomplete/autocomplete.module.ts
  src/angular/button/button.module.ts
  src/angular/datepicker/datepicker.module.ts
  src/angular/header-lean/header.module.ts
  src/angular/menu/menu.module.ts
  src/angular/notification/notification.module.ts
  src/angular/processflow/processflow.module.ts
  src/angular/search/search.module.ts
  src/angular/select/select.module.ts
  src/angular/status/status.module.ts
  src/angular/tag/tag.module.ts
  src/angular/toggle/toggle.spec.ts
  src/angular/tooltip/tooltip.module.ts
  src/angular/usermenu/usermenu.module.ts
  src/showcase/app/angular/angular.module.ts
  src/showcase/app/shared/shared.module.ts
Labels: target: 18.x

#2419 fix(angular/sidebar): remove IE animation workaround
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
  src/angular/sidebar/sidebar/sidebar.ts
Labels: target: 18.x

#2421 chore(journey-maps): upgrade maplibre to 4.7.1
  package.json
  src/components-examples/journey-maps/angular/journey-maps-basic/journey-maps-basic-example.css
  src/components-examples/journey-maps/angular/journey-maps-map-navigation/journey-maps-map-navigation-example.css
  src/components-examples/journey-maps/angular/journey-maps-pois-markers/journey-maps-pois-markers-example.css
  src/components-examples/journey-maps/angular/journey-maps-routes-zones/journey-maps-routes-zones-example.css
  src/components-examples/journey-maps/angular/journey-maps-style-options/journey-maps-style-options-example.css
  src/components-examples/journey-maps/angular/journey-maps-ui-options/journey-maps-ui-options-example.css
  src/components-examples/journey-maps/esri-plugin/esri-plugin/esri-plugin-example.css
  src/journey-maps/angular/angular.md
  src/journey-maps/angular/services/map/map-marker-service.ts
  src/journey-maps/angular/services/map/map-service.ts
  src/journey-maps/esri-plugin/esri-plugin.md
  src/journey-maps/package.json
  src/showcase/app/shared/shared.module.ts
  src/showcase/assets/stack-blitz/package.json
  yarn.lock
Labels: target: 18.x

#2422 refactor(multiple): use ID generator
  src/angular/accordion/expansion-panel.ts
  src/angular/alert/BUILD.bazel
  src/angular/alert/alert-outlet.ts
  src/angular/alert/alert.ts
  src/angular/autocomplete/autocomplete.ts
  src/angular/captcha/BUILD.bazel
  src/angular/captcha/captcha/captcha.ts
  src/angular/checkbox/checkbox.spec.ts
  src/angular/checkbox/checkbox.ts
  src/angular/chips/chip-input.ts
  src/angular/chips/chip-list.ts
  src/angular/core/option/optgroup.ts
  src/angular/core/option/option-hint.ts
  src/angular/core/option/option.ts
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/dialog/dialog-content-directives.ts
  src/angular/dialog/dialog.ts
  src/angular/form-field/BUILD.bazel
  src/angular/form-field/error.ts
  src/angular/form-field/form-field.ts
  src/angular/header-lean/header-menu.ts
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
  src/angular/icon/BUILD.bazel
  src/angular/icon/icon.spec.ts
  src/angular/icon/icon.ts
  src/angular/input/input.spec.ts
  src/angular/input/input.ts
  src/angular/lightbox/lightbox-content-directives.ts
  src/angular/lightbox/lightbox.ts
  src/angular/menu/menu.ts
  src/angular/notification/BUILD.bazel
  src/angular/notification/notification.ts
  src/angular/radio-button/radio-button.ts
  src/angular/search/header-search.ts
  src/angular/search/search.ts
  src/angular/select/select.ts
  src/angular/tabs/tab-nav-bar.ts
  src/angular/tag/tags.spec.ts
  src/angular/textexpand/BUILD.bazel
  src/angular/textexpand/textexpand.ts
  src/angular/toggle/toggle.ts
  src/angular/tooltip/tooltip-wrapper.ts
  src/angular/usermenu/BUILD.bazel
  src/angular/usermenu/usermenu.ts
Labels: target: major, angular-components-sync

#2420 build: update @angular/bazel to latest and resolve errors
  package.json
  src/angular/processflow/processflow.ts
  src/angular/radio-button/radio-button.ts
  src/angular/sidebar/icon-sidebar/icon-sidebar.ts
  src/angular/sidebar/sidebar/sidebar.ts
  src/angular/tooltip/tooltip.ts
  src/bazel-tsconfig-build.json
  src/showcase/app/angular/icon-overview/cdn-icon-list/cdn-icon-list.component.ts
  src/showcase/app/app.component.ts
  src/showcase/app/howtoupdate/how-to-update.component.ts
  tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
  tsconfig.json
  yarn.lock
Labels: target: major, angular-components-sync

#2424 fix(multiple): remove usages of Sass globals
  src/angular/styles/_mediaqueries.scss
Labels: target: 18.x

#2427 fix: add missing CommonModule in showcase
  src/showcase/app/angular/angular.module.ts
Labels: target: 18.x

#2431 fix(angular/form-field): avoid touching the DOM on each state change
  src/angular/form-field/form-field.ts
Labels: angular-components-sync, target: 18.x

#2432 fix(angular/menu): handle keyboard events through dispatcher
  src/angular/menu/menu-trigger.ts
  src/angular/menu/menu.html
  src/angular/menu/menu.spec.ts
  src/angular/menu/menu.ts
Labels: angular-components-sync, target: 18.x

#2433 fix(angular): remove final references to ComponentFactoryResolver
  src/angular/dialog/dialog-config.ts
  src/angular/lightbox/lightbox-config.ts
  src/angular/menu/menu-content.ts
  src/angular/tabs/BUILD.bazel
  src/angular/tabs/tab-body.ts
Labels: angular-components-sync, target: 18.x

#2434 build: prepare the v19 release
  .github/workflows/maintenance-tagging.yml
  packages.bzl
  renovate.json
  src/angular/schematics/migration.json
  src/angular/schematics/ng-update/index.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
  src/showcase/app/howtoupdate/update-steps.ts
  src/showcase/assets/stack-blitz/package-lock.json
  src/showcase/assets/stack-blitz/package.json
Labels: target: major
