Repository sbb-design-systems/sbb-angular, pull requests merged in 2024-04, with the labels that each got.

#2227 fix(angular/tooltip): allow disabling tooltips
  src/angular/styles/_typography.scss
  src/angular/tooltip/tooltip-wrapper.html
  src/angular/tooltip/tooltip-wrapper.spec.ts
  src/angular/tooltip/tooltip-wrapper.ts
  src/angular/tooltip/tooltip.md
  src/components-examples/angular/tooltip/BUILD.bazel
  src/components-examples/angular/tooltip/tooltip-simple/tooltip-simple-example.html
  src/components-examples/angular/tooltip/tooltip-simple/tooltip-simple-example.ts
Labels: preview-available, target: 17.x

#2236 refactor(angular/chips): remove use of zone onStable for blur events
  src/angular/chips/chip-list.spec.ts
  src/angular/chips/chip.ts
Labels: preview-available, target: 17.x

#2232 build: update to Angular v18 next
  .nvmrc
  WORKSPACE
  package.json
  src/angular/schematics/ng-update/index.ts
  src/angular/schematics/ng-update/migrations/sbb-angular-symbols.json
  src/angular/schematics/ng-update/migrations/secondary-entry-points-migration.ts
  src/angular/table/table.spec.ts
  src/angular/table/table/table.ts
  yarn.lock
Labels: preview-available

#2243 test(tabs): fix test to enable next angular version
  src/angular/tabs/tab-header.spec.ts
Labels: preview-available, target: 17.x

#2219 fix(angular/core): mark fields on HasErrorState as nullable
  src/angular/core/common-behaviors/error-state.ts
Labels: preview-available, target: 17.x

#2235 chore: adjust deprecation target version
  src/angular/core/common-behaviors/disabled.ts
  src/angular/core/common-behaviors/error-state.ts
  src/angular/core/common-behaviors/initialized.ts
  src/angular/core/common-behaviors/tabindex.ts
  src/angular/sidebar/sidebar-base.ts
Labels: preview-available, target: 17.x

#2234 fix(angular/tabs): use ResizeObserver to react to size changes
  src/angular/tabs/paginated-tab-header.ts
  src/angular/tabs/tab-header.spec.ts
  tslint.json
Labels: preview-available, target: 17.x

#2220 refactor(angular/datepicker): remove use of zone onStable for focus a…
  src/angular/datepicker/calendar-body/calendar-body.ts
  src/angular/datepicker/datepicker/datepicker.ts
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
Labels: target: major, preview-available
