Repository sbb-design-systems/sbb-angular, pull requests merged in 2025-05, with the labels that each got.

#2518 test: use correct import order in angular-test.init.ts
  test/angular-test.init.ts
Labels: target: major

#2519 refactor(angular/autocomplete): switch to tree-shakeable overlay APIs
  src/angular/autocomplete/autocomplete-trigger.ts
  src/angular/autocomplete/autocomplete.spec.ts
Labels: target: major

#2528 fix(multiple): fix VoiceOver confused by Select/Autocomplete's ARIA semantics
  src/angular/autocomplete/autocomplete-trigger.ts
  src/angular/autocomplete/autocomplete.spec.ts
  src/angular/select/select.spec.ts
  src/angular/select/select.ts
Labels: target: major, angular-components-sync

#2529 build: set up schematics for v20
  src/angular/schematics/migration.json
  src/angular/schematics/ng-update/index.ts
Labels: target: major

#2532 build: update dependency node to v22.15.1
  .nvmrc
Labels: target: major, angular-components-sync

#2533 chore: update to latest renovate
  package.json
  pnpm-lock.yaml
Labels: target: 19.x

#2534 build: update dependency @bazel/runfiles to v6
  package.json
  pnpm-lock.yaml
Labels: target: 19.x

#2541 docs: migrate stackblitz to standalone
  docs/src/app/shared/component-viewer/stack-blitz/stack-blitz-writer.ts
  docs/src/assets/stack-blitz/src/app/app.module.ts
  docs/src/assets/stack-blitz/src/main.ts
Labels: target: major

#2546 build: fix location meta information
  scripts/build.mts
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
Labels: target: 19.x

#2554 ci: fix renovate's post upgrade task
  renovate.json
Labels: target: major
