Repository sbb-design-systems/sbb-angular, pull requests merged in 2025-06, with the labels that each got.

#2555 build: update to Angular v20 final
  docs/src/assets/stack-blitz/package-lock.json
  docs/src/assets/stack-blitz/package.json
  pnpm-workspace.yaml
Labels: target: major

#2531 fix(angular/sidebar): removes -1 tabindex from sidenav in "over" mode
  src/angular/i18n/xlf/messages.xlf
  src/angular/i18n/xlf2/messages.xlf
  src/angular/sidebar/sidebar/sidebar.ts
Labels: target: 19.x

#2558 test(multiple): enable exhaustive checks
  src/angular/accordion/accordion.spec.ts
  src/angular/notification-toast/notification-toast.spec.ts
Labels: target: major

#2563 ci: build docs with `--config=release`
  scripts/build.mts
Labels: target: 20.x

#2567 feat(journey-maps): add new poi subcategory 'sharing_zone'
  src/journey-maps/angular/journey-maps.interfaces.ts
Labels: target: 20.x

#2568 docs: update documentation for journey maps web component
  src/journey-maps-wc/getting-started.md
Labels: target: 20.x

#2572 build: update dependency karma-jasmine-html-reporter to v2
  docs/package.json
  pnpm-lock.yaml
  src/journey-maps-wc/package.json
Labels: angular-components-sync, target: 20.x
